# Generated by Django 6.0.6 on 2026-06-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('video_title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('video_quality', models.CharField(choices=[('360p', '360p'), ('720p', '720p'), ('1080', '1080p')], default='CASH', max_length=20)),
                ('thumbnail', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
