# Generated by Django 6.0.6 on 2026-06-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videxapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vide',
        ),
        migrations.AddField(
            model_name='videocreation',
            name='video_file',
            field=models.FileField(default='', upload_to='videos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videocreation',
            name='date_created',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='videocreation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocreation',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='videocreation',
            name='video_quality',
            field=models.CharField(choices=[('360p', '360p'), ('720p', '720p'), ('1080p', '1080p')], default='360p', max_length=20),
        ),
    ]
